SET SERVEROUTPUT ON;

DECLARE 
    user_exists NUMBER;
BEGIN
    SELECT COUNT(*) INTO user_exists
    FROM all_users
    WHERE username = 'BASIC_USER';

    -- Drop the User if the user already exists 
    IF user_exists > 0 THEN 
        EXECUTE IMMEDIATE 'DROP USER BASIC_USER CASCADE';
        DBMS_OUTPUT.PUT_LINE('USER BASIC_USER DROPPED');
    END IF;

    -- Create the user with a password that contains special characters, enclosed in double quotes
    EXECUTE IMMEDIATE 'CREATE USER BASIC_USER IDENTIFIED BY "dbms#BasicUser1@ApiGateway"';
    DBMS_OUTPUT.PUT_LINE('USER BASIC_USER CREATED');

    -- Grant Basic connect permission
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO BASIC_USER';
    DBMS_OUTPUT.PUT_LINE('GRANTED CREATE SESSION TO USER BASIC_USER');
    
    -- Grant Read Access to all specific tables
    EXECUTE IMMEDIATE 'GRANT SELECT ON API TO BASIC_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON PRICING_MODEL TO BASIC_USER';
    EXECUTE IMMEDIATE 'GRANT SELECT ON user_dashboard TO BASIC_USER';
    DBMS_OUTPUT.PUT_LINE('GRANTED READ ACCESS TO USER BASIC_USER');
    
    -- Grant Full access to REQUESTS table
    EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE, DELETE ON REQUESTS TO BASIC_USER';
    DBMS_OUTPUT.PUT_LINE('GRANTED FULL ACCESS TO USER BASIC_USER FOR REQUESTS TABLE ONLY');
   
    -- Grant quota on tablespace (necessary for INSERT operations)
    EXECUTE IMMEDIATE 'ALTER USER BASIC_USER QUOTA 5M ON REQUESTS'; 
    DBMS_OUTPUT.PUT_LINE('5MB MEMORY ALLOCATION PROVIDED TO USER BASIC_USER');

EXCEPTION
    WHEN OTHERS THEN
       DBMS_OUTPUT.PUT_LINE('Something went wrong! Try again.');
        
END;